Repository stashapp/stash-box, pull requests merged in 2023-06, with the labels that each got.

#650 README: clarify that direct TLS for SMTP is not supported, STARTTLS is.
  README.md
Labels: documentation

#644 [Documentation] Add Matrix, update README, add more badges
  README.md
Labels: documentation

#647 Fix for strict Yup casts (#645)
  frontend/src/pages/performers/performerForm/PerformerForm.tsx
  frontend/src/pages/scenes/sceneForm/SceneForm.tsx
  frontend/src/pages/studios/studioForm/StudioForm.tsx
Labels: bug

#654 Validate image location on file backed WriteFile
  pkg/image/file.go
Labels: bug

#658 Allow configuration of s3 upload headers
  README.md
  pkg/image/s3.go
  pkg/manager/config/config.go
Labels: enhancement

#659 add error propagation and logging in favicon-related functions
  Makefile
  pkg/api/routes_image.go
  pkg/image/favicon.go
  pkg/manager/config/config.go
Labels: chore
